### ISSUE TITLE
Better logging and error raising

### ISSUE THREAD

**Issue by AreelKhan** [science-gpt/science-gpt#18]
at the moment none of my code even handles errors (it just fails without even trying to explain why). I dont know how much every one else has focused on good logging and error handling.

**Comment by AreelKhan** [comment]
using correlations would be useful (more context to come)

**Comment by carterdemars** [comment]
I haven't added logging yet, but I figure for now we can just output logs to the command line until we decide where we will store them?

**Comment by AreelKhan** [comment]
> I haven't added logging yet, but I figure for now we can just output logs to the command line until we decide where we will store them?

Yes i think that does the trick for the time being

**Comment by AreelKhan** [comment]
Kinda done, dont think this is specific enough and doesnt matter as much. closing
