### ISSUE TITLE
Streamlit reload causes re-insertion of all documents

### ISSUE THREAD

**Issue by AreelKhan** [science-gpt/science-gpt#24]
Every time streamlit reruns the app.py script, all the documents inside data/ directory get re-inserted into the vectorstore. 

The good this is we dont get duplicates because the chroma db does not allow re-insertion of a document with the same id. However, this may not be the case for all db vendors. 

The main concern is that of repeated computation, we should not be passing all our documents through the insertion pipeline every time the page is refreshed.

**Comment by spencer-crook** [comment]
Yeah, I think it makes sense to have logic to try to connect and read from DB as the "init" rather than the process of chunking / embedding, adding to DB as the init. 

I think these should be separate functions we can call which do not necessarily run on init

**Comment by bing1100** [comment]
This should be fixed with our new release 👍 
I made it so chunks that have been loaded already don't get reloaded in the ChromaDB
